// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#define SECRET_DEVICE_KEY ""

#define SECRET_OPTIONAL_PASS ""
#define SECRET_SSID "Hong"
#define SECRET_HOST ""
#define SECRET_PORT 

const char DEVICE_LOGIN_NAME[]  = "4e2a1e1b-e0c8-40b3-a902-53f1dae42818";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password
const char HOST[]               = SECRET_HOST;
const int PORT                 = SECRET_PORT;



void onMsgFromPhoneChange();
void onRGBChange();
void onLightSwitchChange();

String msgFromPhone;
CloudColoredLight rGB;
CloudSwitch lightSwitch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(msgFromPhone, READWRITE, ON_CHANGE, onMsgFromPhoneChange);
  ArduinoCloud.addProperty(rGB, READWRITE, ON_CHANGE, onRGBChange);
  ArduinoCloud.addProperty(lightSwitch, READWRITE, ON_CHANGE, onLightSwitchChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);